name: "Raina Chrobak"
output_dir: "."
navbar:
  title: "Raina Chrobak"
  left:
    - text: "Resume"
      href: RainaChrobak_Resume.pdf

  right:
    - icon: fa-envelope fa-lg
      href: contact.html
    - icon: fa-github fa-lg
      href: http://github.com/rainachrobak
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/raina-chrobak-7aa5b16/
output:
  html_document:
    theme: paper
    css: 'styles.css'
